(load "pandoc.chicken.scm")
(import (chicken pretty-print)
        (only (sxml-transforms) SXML->HTML)
        (pandoc))
(SXML->HTML (pandoc-file->sxml 'gfm "test/CharEq.md"))
(newline)
(newline)
(SXML->HTML (pandoc-file->sxml 'gfm "test/VoidValue.md"))
(newline)
(newline)
(pretty-print (pandoc-file->json 'gfm "test/VoidValue.md"))
